config/routes.rb
Rails.application.routes.draw do
  resources :batch_montages, only: [:new, :create, :show]
  resources :montages, only: [:show], constraints: { format: 'jpg' }
  root to: 'batch_montages#new'

  get 'batch_montages' => redirect('/')
end

app/models/batch_montage.rb
# == Schema Information
#
# Table name: batch_montages
#
#  id         :integer          not null, primary key
#  status     :string
#  created_at :datetime
#  updated_at :datetime
#

class BatchMontage <  ActiveRecord::Base
  has_many :montages
  enum status: [ :done, :todo ]

  after_create :process_batch

  def process_batch
    montages.todo.each do |montage|
      montage.delay.perform
    end
  end

  def check_status
    if montages.todo.count == 0
      self.status = "done"
      self.save
    end
  end

  def percentage
    ((montages.done.count / montages.count.to_f) * 100).round
  end

  def to_json
    {id: id, percentage: percentage, status: status}
  end

  def to_csv
    require 'csv'
    
    CSV.generate do |csv|
      montages.all.each do |montage|
        csv << [montage.path]
      end
    end
  end
end

app/models/montage.rb
# == Schema Information
#
# Table name: montages
#
#  id               :integer          not null, primary key
#  photo_url_1      :string           not null
#  photo_url_2      :string           not null
#  batch_montage_id :integer          not null
#  status           :string           not null
#  created_at       :datetime
#  updated_at       :datetime
#  path             :string
#

class Montage <  ActiveRecord::Base
  belongs_to :batch_montage

  validates :photo_url_1, presence: true
  validates :photo_url_2, presence: true

  enum status: [ :done, :todo, :with_error ]

  def perform
    require "open-uri"

    images = Magick::ImageList.new

    # read image from http
    urlimage_1 = open(photo_url_1)
    urlimage_2 = open(photo_url_2)
    images.from_blob(urlimage_1.read)
    images.from_blob(urlimage_2.read)

    # read logo
    logo = Magick::ImageList.new(Rails.root.join('app', 'assets', 'images', 'generic_logo.png'))

    # launch service
    montage_service = MontageService.new(image_1: images[0], image_2: images[1], logo: logo[0], margin: 20)

    assemble = montage_service.assemble
    assemble.format = "jpg"

    # push the controller that display the img by the base
    self.path = HOST + "/montages/" + id.to_s + ".jpg"

    # trick to avoid S3 for heroku, we save the base64 in database
    self.base64 = Base64.encode64(assemble.to_blob)

    # push the local path
    # path_output_file = Rails.root.join('public', 'photos', "montage_" + id.to_s + '.jpg')
    # assemble = montage_service.assemble(path_output_file)
    # self.path = HOST + "/photos/montage_" + id.to_s + '.jpg'    
    # self.base64 = Base64.encode64(open(path_output_file).read)

    self.status = "done"
    self.save

    self.batch_montage.check_status
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/batch_montages_controller.rb
class BatchMontagesController < ApplicationController

  def new
    @batch_montage = BatchMontage.new
  end

  def create
    require 'csv'
    @batch_montage = BatchMontage.new(status: "todo")

    if params[:file]
      content_file = File.read(params[:file].path)

      if content_file.index(';')
        separator = ';'
      elsif  content_file.index("\t")
        separator = "\t"
      else
        separator = ','
      end

      begin
        CSV.parse(content_file, {:col_sep => separator}) do |row|
          @batch_montage.montages.build( photo_url_1: row[0],
                                         photo_url_2: row[1],
                                         status: "todo" )
        end

        @batch_montage.save
        flash[:error] = nil
        redirect_to batch_montage_url(@batch_montage)
      rescue
        flash[:error] = "Can't parse the CSV file"
        render :new
      end

    end
  end

  def show
    @batch_montage = BatchMontage.find(params[:id])
    respond_to do |format|
      format.json do
        render json: @batch_montage.to_json
      end

      format.csv do
        send_data @batch_montage.to_csv, file_name: "export.csv"
      end

      format.html do
        render
      end
    end
  end


end

app/controllers/montages_controller.rb
class MontagesController < ApplicationController
  def show
    @montage = Montage.find(params[:id])

    respond_to do |format|
      format.jpg do
        render text: Base64.decode64(@montage.base64)
      end
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/batch_montages/new.html.erb
<br/>
<%= form_tag(batch_montages_path, multipart: true) do %>
  <%= label_tag :file, 'File to send' %>
  <%= file_field_tag :file, as: :file %><br/>
  <%= submit_tag 'Send' %>
<% end %>

app/views/batch_montages/show.html.erb
<br/>

<% if @batch_montage.todo? %>
  <div>
    Progression: <span id="percentage"></span>%
  </div>

  <script>
    get_percentage(<%= @batch_montage.id %>);
  </script>
<% else %>
  <div>
    DONE :
    <%= link_to "Download CSV",
      batch_montage_path(@batch_montage, format: :csv)
     %>
    <br/><br/>
    <%= link_to "Launch a new batch", "/" %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Silkfred</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <div class="page-header">
      <h1><img src="http://img.clubic.com/0080008006639344-c2-photo-oYToxOntzOjU6ImNvbG9yIjtzOjU6IndoaXRlIjt9-panda-sa-cutity-logo.jpg" />
          Batch
      </h1>
    </div>

    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>

    <%= yield %>

  </div>
</body>
</html>